#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#
before_build:
  appveyor-retry nuget restore
  
#---------------------------------#
#       tests configuration       #
#---------------------------------#
test:
  assemblies:
    - XmpCore.Tests.dll
